// GENERATED by tool/gen_solar_font.py — do not edit by hand.
// Solar icon set (CC BY 4.0, https://www.figma.com/community/file/1166831539721848736)
import 'package:flutter/widgets.dart';

class SolarIcons {
  SolarIcons._();

  static const _family = 'SolarIcons';

  /// add-circle-outline
  static const IconData add = IconData(0xE800, fontFamily: _family);
  /// archive-outline
  static const IconData archive = IconData(0xE801, fontFamily: _family);
  /// bell-outline
  static const IconData bell = IconData(0xE802, fontFamily: _family);
  /// forbidden-circle-outline
  static const IconData block = IconData(0xE803, fontFamily: _family);
  /// bolt-outline
  static const IconData bolt = IconData(0xE804, fontFamily: _family);
  /// cat-bold
  static const IconData cat = IconData(0xE805, fontFamily: _family);
  /// check-circle-outline
  static const IconData check = IconData(0xE806, fontFamily: _family);
  /// alt-arrow-down-outline
  static const IconData chevronDown = IconData(0xE807, fontFamily: _family);
  /// alt-arrow-right-outline
  static const IconData chevronRight = IconData(0xE808, fontFamily: _family);
  /// clock-circle-outline
  static const IconData clock = IconData(0xE809, fontFamily: _family);
  /// close-circle-outline
  static const IconData close = IconData(0xE80A, fontFamily: _family);
  /// copy-outline
  static const IconData copy = IconData(0xE80B, fontFamily: _family);
  /// cpu-bolt-outline
  static const IconData cpu = IconData(0xE80C, fontFamily: _family);
  /// moon-outline
  static const IconData darkMode = IconData(0xE80D, fontFamily: _family);
  /// monitor-outline
  static const IconData desktop = IconData(0xE80E, fontFamily: _family);
  /// devices-bold
  static const IconData devices = IconData(0xE80F, fontFamily: _family);
  /// devices-outline
  static const IconData devicesOutline = IconData(0xE810, fontFamily: _family);
  /// confetti-minimalistic-outline
  static const IconData done = IconData(0xE811, fontFamily: _family);
  /// square-arrow-down-outline
  static const IconData download = IconData(0xE812, fontFamily: _family);
  /// pen-2-outline
  static const IconData edit = IconData(0xE813, fontFamily: _family);
  /// eye-outline
  static const IconData eye = IconData(0xE814, fontFamily: _family);
  /// file-outline
  static const IconData file = IconData(0xE815, fontFamily: _family);
  /// music-note-3-outline
  static const IconData fileAudio = IconData(0xE816, fontFamily: _family);
  /// gallery-outline
  static const IconData fileImage = IconData(0xE817, fontFamily: _family);
  /// document-text-outline
  static const IconData fileText = IconData(0xE818, fontFamily: _family);
  /// video-frame-outline
  static const IconData fileVideo = IconData(0xE819, fontFamily: _family);
  /// zip-file-outline
  static const IconData fileZip = IconData(0xE81A, fontFamily: _family);
  /// folder-outline
  static const IconData folder = IconData(0xE81B, fontFamily: _family);
  /// folder-with-files-outline
  static const IconData folderFiles = IconData(0xE81C, fontFamily: _family);
  /// global-outline
  static const IconData globe = IconData(0xE81D, fontFamily: _family);
  /// history-2-bold
  static const IconData history = IconData(0xE81E, fontFamily: _family);
  /// history-2-outline
  static const IconData historyOutline = IconData(0xE81F, fontFamily: _family);
  /// info-circle-outline
  static const IconData info = IconData(0xE820, fontFamily: _family);
  /// laptop-2-outline
  static const IconData laptop = IconData(0xE821, fontFamily: _family);
  /// sun-outline
  static const IconData lightMode = IconData(0xE822, fontFamily: _family);
  /// link-round-outline
  static const IconData link = IconData(0xE823, fontFamily: _family);
  /// shield-keyhole-outline
  static const IconData lock = IconData(0xE824, fontFamily: _family);
  /// menu-dots-outline
  static const IconData more = IconData(0xE825, fontFamily: _family);
  /// pause-circle-outline
  static const IconData pause = IconData(0xE826, fontFamily: _family);
  /// smartphone-2-outline
  static const IconData phone = IconData(0xE827, fontFamily: _family);
  /// play-circle-outline
  static const IconData play = IconData(0xE828, fontFamily: _family);
  /// plug-circle-outline
  static const IconData port = IconData(0xE829, fontFamily: _family);
  /// qr-code-outline
  static const IconData qr = IconData(0xE82A, fontFamily: _family);
  /// inbox-in-outline
  static const IconData receive = IconData(0xE82B, fontFamily: _family);
  /// refresh-outline
  static const IconData refresh = IconData(0xE82C, fontFamily: _family);
  /// rocket-2-outline
  static const IconData rocket = IconData(0xE82D, fontFamily: _family);
  /// wi-fi-router-outline
  static const IconData router = IconData(0xE82E, fontFamily: _family);
  /// code-scan-outline
  static const IconData scan = IconData(0xE82F, fontFamily: _family);
  /// magnifer-outline
  static const IconData search = IconData(0xE830, fontFamily: _family);
  /// inbox-out-outline
  static const IconData send = IconData(0xE831, fontFamily: _family);
  /// server-2-outline
  static const IconData server = IconData(0xE832, fontFamily: _family);
  /// settings-bold
  static const IconData settings = IconData(0xE833, fontFamily: _family);
  /// settings-outline
  static const IconData settingsOutline = IconData(0xE834, fontFamily: _family);
  /// share-outline
  static const IconData share = IconData(0xE835, fontFamily: _family);
  /// shield-check-outline
  static const IconData shield = IconData(0xE836, fontFamily: _family);
  /// star-outline
  static const IconData starOff = IconData(0xE837, fontFamily: _family);
  /// star-bold
  static const IconData starOn = IconData(0xE838, fontFamily: _family);
  /// stop-circle-outline
  static const IconData stop = IconData(0xE839, fontFamily: _family);
  /// square-transfer-horizontal-outline
  static const IconData swap = IconData(0xE83A, fontFamily: _family);
  /// refresh-circle-outline
  static const IconData sync = IconData(0xE83B, fontFamily: _family);
  /// tablet-outline
  static const IconData tablet = IconData(0xE83C, fontFamily: _family);
  /// user-circle-outline
  static const IconData thisDevice = IconData(0xE83D, fontFamily: _family);
  /// stopwatch-outline
  static const IconData timer = IconData(0xE83E, fontFamily: _family);
  /// transfer-horizontal-outline
  static const IconData transfer = IconData(0xE83F, fontFamily: _family);
  /// trash-bin-trash-outline
  static const IconData trash = IconData(0xE840, fontFamily: _family);
  /// tuning-2-outline
  static const IconData tune = IconData(0xE841, fontFamily: _family);
  /// box-outline
  static const IconData unknownDevice = IconData(0xE842, fontFamily: _family);
  /// square-arrow-up-outline
  static const IconData upload = IconData(0xE843, fontFamily: _family);
  /// danger-triangle-outline
  static const IconData warn = IconData(0xE844, fontFamily: _family);
  /// wi-fi-router-round-outline
  static const IconData wifi = IconData(0xE845, fontFamily: _family);
}
